vCenter = "vcdr01.ldc.int"
userName = "administrator@vsphere.local"
password = "VMware1!"
datacenter = "DR-DC"
datastore = "LSI-SSD01.local"
cluster = "DR-Cluster"
#nsx-t based network
network = "k8s-nw"
template = "CentOS7-DR"