apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: telegraf-infra
data:
  telegraf.conf: |+
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      logfile = ""
      hostname = "telegraf-infra"
      omit_hostname = false
    [[outputs.prometheus_client]]
      ## Address to listen on.
      listen = ":9273"
    [[inputs.ipmi_sensor]]
      #Recommended: use metric 'interval' that is a multiple of 'timeout' to avoid
      servers = ["ADMIN:ADMIN@lan(172.16.0.12)","ADMIN:ADMIN@lan(192.168.1.11)"]
      interval = "30s"
      timeout = "10s"
    [[inputs.ping]]
      interval = "60s"
      urls = ["8.8.8.8", "letsdocloud.com", "iamgubi.xyz"]
      count = 4
      ping_interval = 1.0
      timeout = 2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: telegraf-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
      type: infra
  template:
    metadata:
      labels:
        app: telegraf
        type: infra
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.5.3-alpine
        ports:
        - name: udp
          protocol: UDP
          containerPort: 8092
        - name: http
          containerPort: 8186
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        resources:
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: config
        configMap:
          name: telegraf-infra