# prep-target hosts for kubeadm
# install depdendency
# test: ansible -i inventory --private-key=/home/master/.ssh/id_rsa -u root -m ping all
# execute 
# ansible-playbook -i inventory --private-key=/home/master/.ssh/id_rsa prep-for-kubeadm.yml
---
- hosts: masters
  remote_user: root
  become: yes

  tasks:
    - name: Create a centos user
      user:
        name: centos
        password: "SHA512"
        state: present
        shell: /bin/bash 
        system: no
        createhome: yes
        home: /home/centos

    - name: initialize the cluster
      # for Flannel
      # shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      # for Calico purpose
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: centos
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/centos/.kube/config
        remote_src: yes
        owner: centos

# Install Flannel
#    - name: install Pod network
#      become: yes
#      become_user: centos
#      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
#      args:
#        chdir: $HOME
#        creates: pod_network_setup.txt

# Install for Calico
    - name: install Pod network
      become: yes
      become_user: centos
      shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: install RBAC
      become: yes
      become_user: centos
      shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml

      
