kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-slow
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin
  # precreate first the storage profile
  storagePolicyName: slow 
